### ISSUE TITLE
Analog gamepad trigger as Steamvr trigger?

### ISSUE THREAD

**Issue by ghost** [mmorselli/Joy2OpenVR#1]
This is fantastic! I am running around in AZ Sunshine with my Cabella's Big Game hunter Xbox 360 controller. The issue is that  I cannot seem to make the trigger on the physical gun function as the trigger on the vive controller. I can only seem to map it as an axis. I have tried Standard Steamvr and Steamvr beta. I am using the latest version of AZ Sunshine with the 2 handed update. I have tried both version 1 and version 2 trackers, in both tracker mode and controller mode. The thumbsticks work perfectly for free locomotion!

**Comment by mmorselli** [comment]
I can confirm the bug with Arizona Sunshine, I'll take a look. Arizona natively supports trakers as Hyperblaster, I don't know why dosn't take trigger command

As a workaround:

- In OpenVR Input Emulator disable the tracker before launching game
- After game starts, in OpenVR Input Emulator redirect Tracker to one controller and adjust offset to match the gun position in space

Just tested and it works. I must admit that until today I have tested this program only with Serious Sam 3 VR (and a modified Cabela TopShot Elite PS3 )

**Comment by ghost** [comment]
So excellent, can't wait to try. To let you know I had the same "trigger not working" issue in the Steamvr interface. I will try with some other games too. Sounds like you are using the PS3 version of the same gun. I called it by the name of the game, not by the controller name.
Thanks for all of your help! This is exactly what a lot of us are looking for!

**Comment by mmorselli** [comment]
as long as you log joystick commands in the main program window it shouldn't make any difference from PS3 or XBOX version, it simply translate this input into OpenVR Input Emulator command line sequence, according to loaded .ini file (you can load different .ini passing its name in the command line). Trigger should work in SteamVR Home, using gun or tools, I did the initial tests in steamVR Home

**Comment by mmorselli** [comment]
oh, well, I tried an xbox 360 gamepad and I understood what you mean. I'll try to fix it

**Comment by ghost** [comment]
Thanks so much, do you have a Patreon or tip jar so I can show my appreciation?

**Comment by mmorselli** [comment]
try the new 0.4b build. You need to change the [trackpad] section in config.ini (or any other .ini) into [axes] like in the example config.ini, so in the trigger axis (zr_axes on my xbox 360 controller) write trigger1 or trigger2 according to steamvr controller id. 

zr_axes = trigger2

Let me know if it works

No Patreon needed, thank you for testing

**Comment by ghost** [comment]
Trigger works! AZ Sunshine is still acting a little funny. When I press the grip button, I can see the hand close but it will not pick anything up. I tested with Cyber Threat and it is a blast with the thumb stick on the pistol grip! Tested with John Wick, felt very good (but no locomotion to test). Thanks for all the hard work on this!

**Comment by ghost** [comment]
Got it working! I just need to do everything in the correct order to make everything play together nicely! I can send you my personal procedure/setup if you are interested.
Thanks again for all of your time! Not sure of the protocol here, should I close this issue or do you?
Have a great time in VR!

**Comment by mmorselli** [comment]
do you mean Arizona Sunshine? Sure, I'm interested.

This software is only a part of other project I will share in details soon. A modified TopShot with recoil and haptic feedback

**VIDEO**
[![Itopshot recoil](https://user-images.githubusercontent.com/5322634/41427667-ea207c76-7007-11e8-91d4-07d7edac252e.jpg)](https://www.youtube.com/watch?v=FFtoxh24-0o)



![topshottracker](https://user-images.githubusercontent.com/5322634/41427272-af76b6fe-7006-11e8-91b2-a48ff93a1121.jpg)

**Comment by ghost** [comment]
Nice! You are on a whole different level! I was just happy to get the buttons working! I am not sure I help, but I will send my notes your way when I get home from work.
 Excellent work, very impressive, I have a ton of questions but will wait for the "unveiling" and see how many are unanswered!

**Comment by ghost** [comment]
These are the steps I took for everything to work properly. 
I made sure the game controller is NOT ON. OpenVRInputEmulator seems to get confused once a non-VR controller is attached and none of the VR controllers show up.

1. Start Steamvr
2. Turn on Tracker(s) and Steamvr controller(s) NO OTHER GAME CONTROLLERS YET
3. Enable offsets in OpenVRInputEmulator
4. Enable Joy2OpenVR
5. Turn on game controller
 
This is the best way I found to get things to work on my system. Let me know if something doesn't make sense or is not logical. 

Thanks a million times for your hard work on this!
